"""empty message

Revision ID: 3968e16b5e36
Revises: 1261e84382ce
Create Date: 2018-10-01 16:49:00.655988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3968e16b5e36'
down_revision = '1261e84382ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('phone', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_student_phone'), 'student', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_phone'), table_name='student')
    op.drop_column('student', 'phone')
    # ### end Alembic commands ###
