"""add nickname

Revision ID: c4f87fb7554b
Revises: 3968e16b5e36
Create Date: 2018-10-01 23:55:58.325652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f87fb7554b'
down_revision = '3968e16b5e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('nickname', sa.String(length=64), nullable=True))
    op.drop_index('ix_student_email', table_name='student')
    op.drop_index('ix_student_phone', table_name='student')
    op.create_unique_constraint(None, 'student', ['nickname'])
    op.create_unique_constraint(None, 'student', ['phone'])
    op.create_unique_constraint(None, 'student', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_constraint(None, 'student', type_='unique')
    op.create_index('ix_student_phone', 'student', ['phone'], unique=True)
    op.create_index('ix_student_email', 'student', ['email'], unique=True)
    op.drop_column('student', 'nickname')
    # ### end Alembic commands ###
